name: Build VyOS LTS

# on: 
#   release:
#     types: [published]
#   push:
#     branches: 
#       - master
# on:
#   push:
#     tags:
#       - 'v*'
on:
  workflow_dispatch  


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1.2.0
      with:
       format: "YYYYMMDDHHmmss"

    - name: Pull vyos-build docker image
      run: |
        docker pull vyos/vyos-build:sagitta
        
    - name: Build iso
      run: |
        git clone -b sagitta --single-branch https://github.com/vyos/vyos-build.git
        cd vyos-build
        docker run --rm --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:sagitta  bash -c 'sudo make clean &&  ./build-vyos-image iso --architecture amd64 --version "1.4.0-${{ steps.date.outputs.time }}"'

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: vyos-build/build/vyos-1.4.0-${{ steps.date.outputs.time }}-amd64.iso
        tag: sagitta-${{ steps.date.outputs.time  }}
        overwrite: true
        file_glob: true
  
